services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${DB_PORT_EXTERNAL}:5432"
    networks:
      - deputy-net

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - deputy-net

  api:
    image: ${DOCKER_USERNAME}/deputy-api:latest
    container_name: deputy-api
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      DB_CONNECTION: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      MINIO_ENDPOINT: nginx:80
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: deputy-files
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      JWT_KEY: ${JWT_KEY}
      Jwt__Issuer: deputyapp
      Jwt__Audience: deputyapp
      Telegram__UseWebhook: "true"
      Telegram__WebhookUrl: https://${PROJECT_DOMAIN}/api/telegram
      INTERNAL_API: http://telegram-api:7000/api/telegram
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase_key.json
      MAPS_TOKEN: ${MAPS_TOKEN}
      ASPNETCORE_URLS: "http://+:7001"
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SMTP: ${SMTP}
      SMTP_PORT: ${SMTP_PORT}
      DB_ENCRYPTION_KEY: ${DB_ENCRYPTION_KEY}
      APP_INTERNAL_SECRET: ${APP_INTERNAL_SECRET}
    networks:
      - deputy-net
    volumes:
      - ./firebase_key.json:/run/secrets/firebase_key.json:ro
    ports:
      - "7001:7001"

#  telegram-api:
#    image: ${DOCKER_USERNAME}/telegram-api:latest
#    container_name: telegram-api
#    restart: on-failure
#    depends_on:
#      postgres:
#        condition: service_healthy
#      minio:
#        condition: service_started
#      api:
#        condition: service_started
#    environment:
#      ASPNETCORE_ENVIRONMENT: Development
#      DB_CONNECTION: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
#      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
#      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
#      Telegram__UseWebhook: "true"
#      Telegram__WebhookUrl: https://${PROJECT_DOMAIN}/api/telegram
#      API_ADDRESS: http://deputy-api:7001/api/internal
#      ASPNETCORE_URLS: "http://+:7000"
#    networks:
#      - deputy-net
#    ports:
#      - "7000:7000"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/usr/share/nginx/static:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      # - telegram-api
      - minio
    networks:
      - deputy-net
    restart: unless-stopped

volumes:
  pgdata:
  miniodata:

networks:
  deputy-net:
